codeChallenge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from django.conf.urls.static import static
from django.conf import settings

from codeApp.views import LandingPageView
from security.views import clickjacking_page, secret_key_page, pickling_page, xss_page, csrf_page

urlpatterns = [
    # Apps
    path('admin/', admin.site.urls),
    path('', include('codeApp.urls', namespace='codeApp')),
    path('', include('jSon.urls', namespace='json')),
    path('theater/', include('theater.urls', namespace='theater')),
    # Landing Page
    path('', LandingPageView.as_view(), name='landing-view'),
    path('security/secret_key', secret_key_page),
    path('security/pickling', pickling_page),
    path('security/xss', xss_page),
    path('security/csrf', csrf_page),
    path('security/clickjacking', clickjacking_page),
    # Auth
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jSon/urls.py
from django.urls import path

from . import views

app_name = 'jSon'

urlpatterns = [
    path('authors/', views.AuthorListView.as_view(), name='authors-list'),
    path('authors-create/', views.AuthorCreateView.as_view(), name='author-create'),
    path('authors/<int:pk>/', views.AuthorView.as_view(), name='author-detail'),
]

jSon/views.py
from django.contrib.auth import views
from django.http.response import HttpResponseForbidden, JsonResponse
from django.shortcuts import render, redirect
from django.urls.base import reverse_lazy
from django.views.generic.base import View
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.views.generic.edit import CreateView, FormView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse


from codeApp.models import Author
from codeApp.forms import Author, MessageMeForm

class JsonableResponseMixin:
    """
    Mixin to add JSON support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """
    
    def form_invalid(self, form):
        """ Form Error handler with Json Response"""
        response = super().form_invalid(form)
        if self.request.accepts('text/html'):
            return response
        else:
            return JsonResponse(form.errors, status=400)
    
    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.accepts('text/html'):
            return response
        else:
            return JsonResponse (
                {
                    'pk':self.object.pk
                }
            )

class AuthorCreateView(LoginRequiredMixin, CreateView):
    model = Author
    fields = ['name']
    template_name = 'jSon/author_create.html'
    

class AuthorListView(ListView):
    template_name = 'jSon/author_list.html'
    context_object_name = 'authors'
    paginate_by = 4
    queryset = Author.objects.all()


# Mixing DetailView with FormView
class AuthorDetailView(DetailView):
    model = Author
    template_name = 'jSon/author_detail.html'  

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = MessageMeForm()
        return context
    

class AuthorMessageMeView(SingleObjectMixin, FormView):
    model = Author
    form_class = MessageMeForm
    success_url = reverse_lazy('jSon:authors-list')

    def post(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return HttpResponseForbidden("Request not allowed. Login first to proceed.")
        self.object = self.get_object()
        self.get_context_data()
        return super().post(request, *args, **kwargs)
    
class AuthorView(View):
    def get(self, request, *args, **kwargs):
        view = AuthorDetailView.as_view()
        return view(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        view = AuthorMessageMeView.as_view()
        return view(request, *args, **kwargs)

jSon/templates/jSon/author_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <section>
        <div>
            <form action="." method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit">Create</button>
            </form>
        </div>
    </section>
{% endblock content %}

jSon/templates/jSon/author_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <section class="w-full text-center">
        <div>
            <h1>Author {{ author.name }}</h1>
            <a href="{% url 'jSon:authors-list' %}">Go back to authors</a>
            <ul>
                {% for book in author.book.all %}
                    <li>{{ book.name }}</li>
                {% empty %}
                    <p>No books available for {{ author.name }}</p>
                {% endfor %}
            </ul>
            <hr/>
            <div>
                <form action="." method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="bg-green-200 p-3 rounded-xl hover:bg-green-400" type="submit">Message me</button>
                </form>
                <div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

jSon/templates/jSon/author_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <section>
        <div class="pagination container w-2/3 rounded-3xl border shadow bg-gray-400 mt-5">
            <div class="text-center font-bold">
                <h2>Authors {{ authors.count }}{{ authors|pluralize }}.</h2>
            </div>
            <ol>
              {% for author in page_obj %}
                <li>
                    <a class="text-blue-900 hover:text-blue-600 border-b border-green-200" href="{% url 'jSon:author-detail' author.pk %}">
                        {{ author.name }}
                    </a>
                </li>
              {% endfor %}
            </ol>
            <div class="step-links text-center">
                {% if page_obj.has_previous %}
                    <a class="text-blue-900 hover:text-blue-600 border-b border-green-200" href="?page={{ page_obj.previous_page_number }}">
                        previous
                    </a>
                {% endif %}
    
                <span class="current">
                    Page {{ page_obj.number }} of {{ paginator.num_pages }}.
                </span>
    
                {% if page_obj.has_next %}
                    <a class="text-blue-900 hover:text-blue-600 border-b border-green-200" href="?page={{ page_obj.next_page_number }}">
                        next
                    </a>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock content %}