codeApp/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

app_name = 'codeApp'

from . import views
from .signals import signal_home
urlpatterns = [
    path('book-list/', views.BookListView.as_view(), name='view-books'),
    path('add-book/', views.BookAddView.as_view(), name='add-book'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='view-book'),    
    # This approach applies the decorator on a per-instance basis. 
    path('book/<int:pk>/update/', login_required(views.BookUpdateView.as_view()), name='update-book'),    
    path('book/<int:pk>/delete/', views.BookDeleteView.as_view(), name='delete-book'),    
    path('contact-me/', views.ContactFormView.as_view(), name='contact-form'),
    path('json/', views.JsonTemplateView.as_view(), name='json-data'),
    path('signals/',  signal_home, name='signal-home'),
    # path('book-pag/<int:pk>/', views.BokListView.as_view(), name='book-pag'),
    # path('authors-list/', views.BokListView.as_view(), name='authors-list')
]

codeChallenge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from django.conf.urls.static import static
from django.conf import settings

from codeApp.views import LandingPageView
from security.views import clickjacking_page, secret_key_page, pickling_page, xss_page, csrf_page

urlpatterns = [
    # Apps
    path('admin/', admin.site.urls),
    path('', include('codeApp.urls', namespace='codeApp')),
    path('', include('jSon.urls', namespace='json')),
    path('theater/', include('theater.urls', namespace='theater')),
    # Landing Page
    path('', LandingPageView.as_view(), name='landing-view'),
    path('security/secret_key', secret_key_page),
    path('security/pickling', pickling_page),
    path('security/xss', xss_page),
    path('security/csrf', csrf_page),
    path('security/clickjacking', clickjacking_page),
    # Auth
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jSon/urls.py
from django.urls import path

from . import views

app_name = 'jSon'

urlpatterns = [
    path('authors/', views.AuthorListView.as_view(), name='authors-list'),
    path('authors-create/', views.AuthorCreateView.as_view(), name='author-create'),
    path('authors/<int:pk>/', views.AuthorView.as_view(), name='author-detail'),
]

codeApp/models.py
from django.utils.timezone import now
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser
# from django.contrib.auth import get_user, get_user_model
from django.urls import reverse

# User = get_user_model()
class User(AbstractUser):
    pass

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)    

    def __str__(self):
        return self.user.username

class Author(models.Model):
    name = models.CharField(max_length=50)
    book = models.ManyToManyField('BookModel')
    published = models.IntegerField(default=0)
    data = models.JSONField(null=True)
    

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('jSon:authors-list')
        
    class Meta:
        ordering = ['name']

class BookModel(models.Model):
    name = models.CharField(max_length=100)
    pub_date = models.DateTimeField(default=now)
    user = models.ForeignKey(
        User,
        null=True,
        blank=True, 
        on_delete=models.SET_NULL
    )
    userprofile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    

    def __str__(self):
        return self.name
  

def post_save_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
        
post_save.connect(post_save_created_signal, sender=User)

codeApp/forms.py
from django import forms
from django.core.mail import send_mail
from .models import Author, BookModel, User

class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "password")

class BookModelForm(forms.ModelForm):
    class Meta:
        model = BookModel
        fields = (
            'name', 
            'pub_date',
        )

class AuthorModelForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = "__all__"

class ContactForm(forms.Form):
    name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={
        "class": "text-input-props",
        "placeholder": "Your name",
    }))

    email = forms.EmailField(widget=forms.EmailInput(attrs={
        "class": "text-input-props",
        "placeholder": "Your email address"
    }))
    body = forms.CharField(widget=forms.Textarea(attrs={
        "class": "text-area-props",
        "placeholder": "Your message",
    }))

class MessageMeForm(forms.Form):
        body = forms.CharField(widget=forms.Textarea(attrs={
        "rows":3,
        "cols":6,
        "class": "text-area-props",
        "placeholder": "Leave a message",
    }))

codeApp/views.py
from typing import List
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core import paginator
from django.utils.decorators import method_decorator
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views import generic
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.views import View
from django.views.generic.base import ContextMixin, TemplateResponseMixin
from django.views.generic.edit import ModelFormMixin
from django.views.generic.list import ListView

from codeApp.mixins import JsonTemplateView
from .models import Author, BookModel, User
from codeApp.forms import BookModelForm, ContactForm

 # NOT SO DRY
class LandingPageView(generic.TemplateView):
    template_name = 'landing_page.html'

    def get(self, request, *args, **kwargs):
        resp = super().get(request, *args, **kwargs)
        if not request.session.get('secrets') and not request.session.get('visits'):
            request.session['secrets'] = '|4?:jjrK&Q\'/0lY5FlQn=1St_M,tu87#wn}7Yf4YYe(Hh"K+gy'
            request.session["visits"] = 1
        session = request.session.get('visit')
        print(request.META)
        return resp


# Using Mixins
class BookListView(LoginRequiredMixin, TemplateResponseMixin, View):
    template_name = 'codeApp/list_books.html'

    def get(self, request):
        return render(request, self.template_name, self.get_queryset())

    def get_queryset(self):
        user = self.request.user
        # print(f'{user.userprofile} is an instance of {User} {isinstance(user, User)}')
        queryset = {
            "book_list" : BookModel.objects.filter(user=user),
        }
        return queryset  

    # Method not working as intended.
    # def head(self, *args, **kwargs):
    #     book_list = self.get_queryset().latest('pub_date')
    #     print(book_list)
    #     response = HttpResponse(
    #         headers={'last_modified':book_list.pub_date.ctime()
    #     })
    #     return response

# EVERY instance of this view is decorated 
@method_decorator(login_required, name='dispatch')
class BookAddView(ModelFormMixin, View):
    form_class = BookModelForm
    template_name = "codeApp/add_book.html"

    def get(self, request):
        form = self.form_class()
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()
            #! Sets cookie
            signed_object = signer.sign_object({'Test': 'Cookie'})
            request.set_cookie('object', signed_object, max_age=300)
            
            #! Sets Session
            num_of_visits = request.session.get('num_of_visits', 0) + 1
            request.session['num_of_visits'] = num_of_visits
            if num_of_visits > 4: del(request.session['num_of_visits'])
        return render(request, self.template_name, {'form':form})
    
    def post(self, request, *args, **kwargs):
        user = self.request.user
        form = self.form_class(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            pub_date = form.cleaned_data["pub_date"]
            book = BookModel.objects.create(
                name=name,
                pub_date=pub_date,
                user = user,
                userprofile = user.userprofile
            )
            book.save()
            return HttpResponseRedirect("/book-list/")
        return render(request, self.template_name, {'form':form})

class BookDetailView(ContextMixin, View):
    # model =BookModel
    template_name = 'codeApp/view_book.html'

    def get(self, request, *args, **kwargs):
        context = {'book':self.get_queryset(), 'total_books': self.get_context_data()['adds_extra_context']}
        return render(request, self.template_name, context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['adds_extra_context'] = BookModel.objects.all().count()
        return context

    def get_queryset(self):
        query = BookModel.objects.get(id=self.kwargs['pk'])
        return query
    

# Decorated in the URLconf
class BookUpdateView(View):
    template_name = 'codeApp/update_book.html'
    form_class = BookModelForm

    def get(self, request, *args, **kwargs):
        return render(
            request, self.template_name,{
                'form': self.form_class(instance=self.get_queryset()), 'book':self.get_queryset()
            }
        )
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            book = self.get_queryset()
            book.name = form.cleaned_data['name']
            book.pub_date = form.cleaned_data['pub_date']
            book.save()
            return redirect('codeApp:view-book', pk=self.kwargs['pk'])

        return self.get(request)

    def get_queryset(self):
        query = BookModel.objects.get(id=self.kwargs['pk'])
        return query
    
# View method dispatch decorated
class BookDeleteView(View):
    template_name = 'codeApp/remove_book.html'

    # To decorate every instance of a CBV apply decorator to dispatch()
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {"book":self.get_queryset()})

    def post(self, request, *args, **kwargs):
        book = self.get_queryset()
        book.delete()
        return redirect('/book-list/')

    def get_queryset(self):
        queryset = BookModel.objects.get(id=self.kwargs['pk'])
        return queryset

class ContactFormView(generic.FormView):
    template_name = 'codeApp/contact_form.html'
    form_class = ContactForm
    # success_url = reverse_lazy('codeApp:view-books')

    def form_valid(self, form): 
        send_mail(
            subject = form.cleaned_data['name'],   
            message = form.cleaned_data['body'],
            from_email = form.cleaned_data['email'],
            recipient_list = ['test@gmail.com'],
        )
        return super().form_valid(form)
            

    def get_success_url(self):
        return reverse('codeApp:view-books')

class JsonTemplateView(JsonTemplateView, View):
    model = BookModel
    template_name = 'codeApp/json_date.html'

    
class BokListView(SingleObjectMixin, ListView):
    paginator_by = 2
    templates_name = 'codeApp/list_books_pag.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=BookModel.objects.all())
        return super().get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['book_list'] = self.object
        return context
    
    def get_queryset(self):
        return self.object.author_set.all()

codeApp/templates/codeApp/add_book.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section>
    <div class="container w-2/3 rounded-3xl border shadow bg-gray-400 ">
        <h3>Add new book</h3>
        <a href="{% url 'codeApp:view-books' %}">Go back to books</a>
        <form action='.' method='post'>
            {% csrf_token %}
                <div>
                    {{ form|crispy }}
                </div>
            <button class="bg-green-200 border px-3 py-2 rounded-xl w-1/2 flex-center" type="submit">Add</button>
        </form>
    </div>
</section>
{% endblock %}

codeApp/templates/codeApp/author_list.html
<!-- codeApp/author_list.html -->
{% extends 'base.html' %}
{% block content %}
    <section>
        <div class="container w-2/3 rounded-3xl border shadow bg-gray-400">
            <h1>Authors</h1>
            <a class="rounded-m bg-gray-300 px-3 mx-2" href="{% url 'codeApp:add-book' %}">Add a new book</a>
            <a class="rounded-m bg-gray-300 px-3 mx-2" href="{% url 'codeApp:contact-form' %}">Contact us</a>
            <hr/>
            <ul>
                {{book_list}}
                {% for author in author_list %}
                <li>
                    <a href="{% url 'codeApp:view-book' book.pk %}">{{ author.name }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </section>


{% endblock content %}

codeApp/templates/codeApp/contact_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section>
    <div class="container w-2/3 rounded-3xl border shadow bg-gray-400 ">
        <h3>Contact Form</h3>
        <form action='.' method='post'>
            {% csrf_token %}
                <div>
                    {{ form|crispy }}
                </div>
            <button class="border px-3 py-2 rounded-xl w-1/2 flex-center hover:bg-green-200" type="submit">Send</button>
        </form>
    </div>
</section>
{% endblock %}

codeApp/templates/codeApp/json_date.html
{% extends 'base.html' %}
{% block content %}
    <section>
        <div class="container w-2/3 rounded-3xl border shadow bg-gray-400 ">
            <h1>Json Books</h1>
            <a class="rounded-m bg-gray-300 px-3 mx-2" href="{% url 'codeApp:add-book' %}">Add a new book</a>
            <a class="rounded-m bg-gray-300 px-3 mx-2" href="{% url 'codeApp:contact-form' %}">Contact us</a>
            <hr/>
            <div>
                
            </div>
        </div>
    </section>
{% endblock content %}

codeApp/templates/codeApp/list_books.html
{% extends 'base.html' %}
{% block content %}
    <section>
        <div class="container w-2/3 rounded-3xl border shadow bg-gray-400 ">
            <h1>Books</h1>
            <a href="{% url 'jSon:authors-list' %}">Got to Authors</a>
            <a class="rounded-m bg-gray-300 px-3 mx-2" href="{% url 'codeApp:add-book' %}">Add a new book</a>
            <a class="rounded-m bg-gray-300 px-3 mx-2" href="{% url 'codeApp:contact-form' %}">Contact us</a>
            <hr/>
            <ul>
                {% for book in book_list %}
                <li>
                    <a href="{% url 'codeApp:view-book' book.pk %}">{{ book.name }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock content %}

codeApp/templates/codeApp/list_books_pag.html
{% extends 'base.html' %}
{% block content %}
    <section>
        <div class="container w-2/3 rounded-3xl border shadow bg-gray-400 ">
            <h1>Books</h1>
            <a class="rounded-m bg-gray-300 px-3 mx-2" href="{% url 'codeApp:add-book' %}">Add a new book</a>
            <a class="rounded-m bg-gray-300 px-3 mx-2" href="{% url 'codeApp:contact-form' %}">Contact us</a>
            <hr/>
            <ul>
                {% for book in book_list %}
                <li>
                    <a href="{% url 'codeApp:view-book' book.pk %}">{{ book.name }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock content %}

codeApp/templates/codeApp/remove_book.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <section>
        <div class="container">
            <h1>Are you sure you want to delete {{ book.name }}?</h1>
            <form action="." method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit">Yes</button>
                <a class="del-btn " href="{% url 'codeApp:view-book' book.pk %}">No</a>
            </form>
        </div>
    </section>
{% endblock content %}

codeApp/templates/codeApp/update_book.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <section>
        <div class="container">
            <h1>Update </h1>
            <a href="{% url 'codeApp:view-book' book.pk %}">Go back to {{ book.name }}</a>
            <hr/>
            <form action="." method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit">Update</button>
            </form>
        </div>
    </section>
{% endblock content %}

codeApp/templates/codeApp/view_book.html
{% extends 'base.html' %}
{% block content %}
    <section>
        <div class="container">
            <h3>Total books: {{ total_books }}</h3>
            <a href="{% url 'codeApp:view-books' %}">Go back to books</a>
            <div>
                <p>Book Name: {{ book.name }}</p>
                <p>Was published on: {{ book.pub_date }}</p>
            </div>
            <div>
                <a href="{% url 'codeApp:update-book' book.pk %}">Update</a>
                <a href="{% url 'codeApp:delete-book' book.pk %}">Delete</a>
            </div>
        </div>
    </section>
{% endblock content %}