codeApp/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

app_name = 'codeApp'

from . import views
from .signals import signal_home
urlpatterns = [
    path('book-list/', views.BookListView.as_view(), name='view-books'),
    path('add-book/', views.BookAddView.as_view(), name='add-book'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='view-book'),    
    # This approach applies the decorator on a per-instance basis. 
    path('book/<int:pk>/update/', login_required(views.BookUpdateView.as_view()), name='update-book'),    
    path('book/<int:pk>/delete/', views.BookDeleteView.as_view(), name='delete-book'),    
    path('contact-me/', views.ContactFormView.as_view(), name='contact-form'),
    path('json/', views.JsonTemplateView.as_view(), name='json-data'),
    path('signals/',  signal_home, name='signal-home'),
    # path('book-pag/<int:pk>/', views.BokListView.as_view(), name='book-pag'),
    # path('authors-list/', views.BokListView.as_view(), name='authors-list')
]

codeChallenge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from django.conf.urls.static import static
from django.conf import settings

from codeApp.views import LandingPageView
from security.views import clickjacking_page, secret_key_page, pickling_page, xss_page, csrf_page

urlpatterns = [
    # Apps
    path('admin/', admin.site.urls),
    path('', include('codeApp.urls', namespace='codeApp')),
    path('', include('jSon.urls', namespace='json')),
    path('theater/', include('theater.urls', namespace='theater')),
    # Landing Page
    path('', LandingPageView.as_view(), name='landing-view'),
    path('security/secret_key', secret_key_page),
    path('security/pickling', pickling_page),
    path('security/xss', xss_page),
    path('security/csrf', csrf_page),
    path('security/clickjacking', clickjacking_page),
    # Auth
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jSon/urls.py
from django.urls import path

from . import views

app_name = 'jSon'

urlpatterns = [
    path('authors/', views.AuthorListView.as_view(), name='authors-list'),
    path('authors-create/', views.AuthorCreateView.as_view(), name='author-create'),
    path('authors/<int:pk>/', views.AuthorView.as_view(), name='author-detail'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'css/app.css' %}"/>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <title>100DaysOfCode</title>
</head>
    <body>
        {% include 'nav.html' %}
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/landing_page.html
{% extends 'base.html' %}
{% block content %}
    <section style="margin-top:2em;">
        <div class="container w-2/3 rounded-3xl border shadow bg-gray-400 ">
            <a href="{% url 'codeApp:view-books' %}">To the books</a>
        </div>
    </section>
{% endblock content %}

templates/nav.html
<header>
    <div style="padding-top:2em; margin-left:4em; margin-right: 4em;">
        {% if user.is_authenticated %}
        <p style="display:inline;">Welcome, <b>{{ user.username|title }}</b></p>
        <a class="btn" href="{% url 'logout' %}">Logout</a>
        {% else %}
        <p style="display:inline;">Logged user is Anynomous| Please</p>   
        <a class="btn" href="{% url 'login' %}">Login</a>
        {% endif%}
    </div>
</header>