codeChallenge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from django.conf.urls.static import static
from django.conf import settings

from codeApp.views import LandingPageView
from security.views import clickjacking_page, secret_key_page, pickling_page, xss_page, csrf_page

urlpatterns = [
    # Apps
    path('admin/', admin.site.urls),
    path('', include('codeApp.urls', namespace='codeApp')),
    path('', include('jSon.urls', namespace='json')),
    path('theater/', include('theater.urls', namespace='theater')),
    # Landing Page
    path('', LandingPageView.as_view(), name='landing-view'),
    path('security/secret_key', secret_key_page),
    path('security/pickling', pickling_page),
    path('security/xss', xss_page),
    path('security/csrf', csrf_page),
    path('security/clickjacking', clickjacking_page),
    # Auth
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jSon/urls.py
from django.urls import path

from . import views

app_name = 'jSon'

urlpatterns = [
    path('authors/', views.AuthorListView.as_view(), name='authors-list'),
    path('authors-create/', views.AuthorCreateView.as_view(), name='author-create'),
    path('authors/<int:pk>/', views.AuthorView.as_view(), name='author-detail'),
]

theater/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from . import views

app_name = "theater"

urlpatterns = [
    path('', views.list_countries_view, name="list-view"),
    path('search/', views.search_view, name="search-view"),
    path('dogs/', views.dogs_view, name='dogs-view'),
    path('dogs/<int:dog_pk>/', views.dog_detail_view, name='dog-view'),
    path('dogs/<int:dog_pk>/copy/', views.dog_copy_view, name='dog-view-copy'),
    path('dogs/<int:dog_pk>/delete/', views.dog_delete_view, name='dog-delete'),

]

theater/models.py
import uuid
import datetime
from django.db import models
from django.db.models.fields import BooleanField
from django.utils import timezone
from django.db.models.expressions import Value
from django.db.models.functions import Concat


# class TheaterModel(models.Model):
#     name = models.CharField(max_length=50)
#     contact = models.CharField(max_length=50, default="")
#     address = models.CharField(max_length=100, default="")
#     location = models.CharField(max_length=100)
#     now_showing = models.DateTimeField(auto_now=True)
#     # Relationships

#     def __str__(self):
#         return self.name

# class MovieModel(models.Model):
#     title = models.CharField(max_length=100)
#     ratings = models.IntegerField()
#     genre = models.CharField(max_length=100)
#     description = models.TextField()
#     poster = models.ImageField(upload_to="movie/posters/%Y/%M/%d", null=True, blank=True)
#     release_date = models.DateTimeField()
#     # Relationships
#     trailer = models.OneToOneField("TrailerModel", on_delete=models.CASCADE)

#     def __str__(self):
#         return self.title

# class TrailerModel(models.Model):
#     caption = models.CharField(max_length=200)
#     file = models.FileField(upload_to="movie/trailers/%Y/%M/%d", null=True, blank=True)
#     url = models.URLField(max_length=200, null=True, blank=True)

#     def __str__(self):
#         return self.caption

# class CustomerModel(models.Model):
#     firstname = models.CharField(max_length=50)
#     lastname = models.CharField(max_length=50)
#     email = models.EmailField()
    
#     def __str__(self) -> str:
#         return self.email

# class TicketModel(models.Model):
#     ticket_number = models.UUIDField("Ticket Number", default=uuid.uuid4)
#     customer = models.ForeignKey(CustomerModel, on_delete=models.CASCADE)
#     movie = models.ForeignKey(MovieModel, on_delete=models.CASCADE)
#     seat = models.OneToOneField("SeatModel", on_delete=models.CASCADE)
#     cinemax = models.ForeignKey(
#         TheaterModel, 
#         null=True, 
#         blank=True, 
#         on_delete=models.SET_NULL
#     )
#     def __str__(self):
#         return f'''
#         Ticket for {self.customer}
#         '''

# class SeatModel(models.Model):
#     FRONT_LEFT = "FL"
#     FRONT_MIDDLE = "FM"
#     FRONT_RIGHT = "FR"
#     MID_LEFT = "ML"
#     MID_MIDDLE = "MM"
#     MID_RIGHT  = "MR"
#     BACK_LEFT = "BL"
#     BACK_MIDDLE = "BM"
#     BACK_RIGHT  = "BR"

#     SEAT_POSITION_CHOICES = [
#         (FRONT_LEFT, "FL"),        
#         (FRONT_MIDDLE, "FM"),
#         (FRONT_RIGHT, "FR"),   
#         (MID_LEFT, "ML"),
#         (MID_MIDDLE, "MM"),
#         (MID_RIGHT , "MR"),    
#         (BACK_LEFT, "BL"),        
#         (BACK_MIDDLE, "BM"),
#         (BACK_RIGHT, "BR"),        
#     ]
#     seat_number = models.IntegerField(default=87)
#     seat_position = models.CharField(max_length=2, choices=SEAT_POSITION_CHOICES, default="SELECT SEAT")

#     def __str__(self):
#         return self.seat_position

class CountryModel(models.Model):
    name = models.CharField(max_length=255, default="")
    independent = models.CharField(max_length=4, null=True)

    def __str__(self):
        return self.name

class CityModel(models.Model):
    name = models.CharField(max_length=50, default="")
    population = models.IntegerField()
    jobs = models.IntegerField()
    country = models.ForeignKey(CountryModel, on_delete=models.CASCADE, default=1)


    def __str__(self):
        return self.name

class PersonQuerySet(models.QuerySet):
    """Add annotations to Managers or QuerySet"""
    def annotate_full_name(self):
        """ Creates a dynamic field -> `full_name` and returns it in a QuerySet """
        return self.annotate(
            full_name = Concat(
                'first_name', Value(' '), 'last_name'
            )
        )
class PersonModel(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    birthday = models.DateField(default=timezone.now)
    age = models.IntegerField(default=25)
    job = models.CharField(max_length=100, default="")
    last_donated = models.DateTimeField(default=datetime.datetime.today()-datetime.timedelta(5))
    country = models.ForeignKey(CountryModel, on_delete=models.CASCADE)
    personal = models.UUIDField("Personal Identification Number", default=uuid.uuid4)
    marital_status = models.JSONField('{"MaritalStatus": "Single"}')
    pet = models.JSONField(null=True)

    objects = PersonQuerySet.as_manager()

    @property
    def pin(self):
        return self.personal

    def __str__(self):
        return self.first_name
        
class SearchModel(models.Model):
    search_bar = models.CharField(max_length=50)
    by_country = models.BooleanField(default=False)
    by_age = models.BooleanField(default=False)
    by_job = models.BooleanField(default=False)
    
class DogModel(models.Model):
    name = models.CharField(max_length=20)
    data = models.JSONField(null=True)

    def __str__(self):
        return self.name
    

theater/forms.py
from django import forms

from theater.models import SearchModel

class SearchModelForm(forms.ModelForm):
    class Meta:
        model = SearchModel
        fields = "__all__"

theater/views.py
from datetime import timedelta
from django.db.models import Q, F, ExpressionWrapper, Value
from django.db.models.functions import Coalesce, NullIf
from django.db.models.fields import CharField, DateTimeField
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from theater.models import DogModel, PersonModel

from .forms import SearchModelForm
def search_view(request):
    if request.method == "POST":
        form = SearchModelForm(request.POST)
        if form.is_valid():
            search = form.cleaned_data["search_bar"]
            results = Q(
                Q(name__icontains=search) |
                Q(job__icontains=search)|
                Q(country__name__icontains=search) 
            )
            return render(request, "theater/searchResults.html", {
                "search_results":PersonModel.objects.filter(results), 
                "query":PersonModel.objects.filter(results).query
            })
    return render(request, "theater/search.html", {"form": SearchModelForm()})

def list_countries_view(request):
    can = PersonModel.objects.annotate(
        can_donate_on = ExpressionWrapper(
            F('last_donated') - timedelta(days=56), output_field=DateTimeField())
    )
    full_name_view(request)
    return render(request, "theater/index.html", {'can': can})

# Database functions
# Performance Importance
def full_name_view(request):
    full_nameAnno = PersonModel.objects.annotate_full_name().filter(full_name__icontains="n").values_list("full_name")
    # Annotate creating dynamic field
    marital = PersonModel.objects.annotate(
        # ExpressionWrapper wraps expressions when mixed types  
        status=ExpressionWrapper(
            # Coelesce gets non-null values in a list
            Coalesce(
                # Return a null value is argument1 equals arguement2 otherwise return arguement1
                NullIf("marital_status", Value(" ")), "pet"
        ), output_field=CharField())
    ).values_list("status")
    print(marital)

def dogs_view(request):
    dogs=DogModel.objects.all()
    return render(request, 'theater/dogs.html', {'dogs':dogs})

def dog_detail_view(request, dog_pk):
    dog = DogModel.objects.get(id=dog_pk)
    return render(request, 'theater/copies.html', {"dog":dog})

def dog_copy_view(request, dog_pk):
    """ Makes a copy of an object"""
    dog = DogModel.objects.get(id=dog_pk)
    dog.id = None
    dog._state.adding = True
    dog.name = f"Copy_of_{dog.name}" 
    dog.save()
    return HttpResponseRedirect(reverse('theater:dogs-view'))

def dog_delete_view(request, dog_pk):
    dog = DogModel.objects.get(id=dog_pk)
    dog.delete()
    return render(request, 'theater/delete.html')

theater/templates/theater/copies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Copies</title>
</head>
<body>
    <div>
        <p>{{ dog.name }}</p>
        <p>{{ dog.data }}</p>
        <a href="{% url 'theater:dog-view-copy' dog.id %}">Make a copy</a>
        || <a href="{% url 'theater:dog-delete' dog.id %}">Delete</a>
    </div>
</body>
</html>

theater/templates/theater/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Copies</title>
</head>
<body>
    <div>
        <p>Are you sure you want to delete{{ dog }}?</p>
        <a href="{% url 'theater:dogs-view' %}">Yes</a>
    </div>
</body>
</html>

theater/templates/theater/dogs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Copies</title>
</head>
<body>
    <div>
        <ul>
            {% for dog in dogs %}
            <li><a href="{% url 'theater:dog-view' dog.id %}">{{ dog }}</a></li>
            {% endfor %}
        </ul>
    </div>
</body>
</html> 

theater/templates/theater/index.html
{% for person in can %}
<pre>
    <p>person: {{ person.name }}</p>
        <span>can donate on: {{ person.can_donate_on.date }}</span>
        <span>Last donation: {{ person.last_donated}}</span>
</pre>
{% endfor %}

theater/templates/theater/search.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Engine</title>
</head>
<body>
    <main>
        <form method="post" action="#">
            {% csrf_token %}
            {{ form|crispy}}
            <button type="submit">Search</button>
        </form>
    </main>
</body>
</html>

theater/templates/theater/searchResults.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Results</title>
</head>
<body>
    {% for person in search_results %}
<pre>
    <p>person: {{ person.name }}</p>
        <span>can donate on: {{ person.can_donate_on.date }}</span>
        <span>Last donation: {{ person.last_donated}}</span>
</pre>
<hr/>
{{query}}
{% endfor %}
</body>
</html>